---
- name: Add virtualbox apt key
  become: true
  become_user: root
  with_items: '{{ virtualbox_keys }}'
  ansible.builtin.apt_key:
    url: '{{ virtualbox_key_mirror }}/{{ item.name }}'
    id: '{{ item.id }}'

- name: Add virtualbox apt repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    update_cache: true
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
